name: Build OPKG Index and Deploy to gh-pages branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fix script line endings
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix
          dos2unix ./opkg-utils/opkg-make-index

      - name: Make opkg-make-index executable
        run: chmod +x ./opkg-utils/opkg-make-index
        shell: bash

      - name: Generate OPKG Indexes
        run: |
          mkdir -p build
          for arch_dir in all armv7ahf-neon mips32el; do
            if [ -d "$arch_dir" ]; then
              echo "✅ Found and processing directory: $arch_dir"
              mkdir -p "build/$arch_dir"
              ./opkg-utils/opkg-make-index "$arch_dir" > "build/$arch_dir/Packages"
              gzip -c "build/$arch_dir/Packages" > "build/$arch_dir/Packages.gz"
              rm "build/$arch_dir/Packages"
              cp -r "$arch_dir"/* "build/$arch_dir/" || true
            else
              echo "ℹ️ Directory $arch_dir does not exist, skipping."
            fi
          done
        shell: bash

      - name: Validate OPKG Packages
        run: |
          for arch_dir in all armv7ahf-neon mips32el; do
            if [ -f "build/$arch_dir/Packages.gz" ]; then
              echo "🔍 Checking build/$arch_dir/Packages.gz..."
              if [ ! -s "build/$arch_dir/Packages.gz" ]; then
                echo "❌ ERROR: build/$arch_dir/Packages.gz is empty!"
                exit 1
              fi
              PKG_COUNT=$(gunzip -c "build/$arch_dir/Packages.gz" | grep -c "^Package:")
              if [ "$PKG_COUNT" -eq 0 ]; then
                echo "❌ ERROR: build/$arch_dir/Packages.gz does not contain any package entries!"
                exit 1
              fi
              echo "✅ build/$arch_dir/Packages.gz is valid — found $PKG_COUNT packages."
            fi
          done

      - name: Generate HTML index with package links
        run: |
          echo '<!DOCTYPE html>' > build/index.html
          echo '<html lang="pl">' >> build/index.html
          echo '<head>' >> build/index.html
          echo '  <meta charset="UTF-8" />' >> build/index.html
          echo '  <title>Repozytorium OPKG - Azman</title>' >> build/index.html
          echo '  <style>body{font-family:Arial, sans-serif;margin:20px;} h1{color:#2a2a2a;} h2{margin-top:30px;} ul{list-style:disc;margin-left:20px;} pre{background:#f4f4f4;padding:10px;border-radius:6px;}</style>' >> build/index.html
          echo '</head>' >> build/index.html
          echo '<body>' >> build/index.html
          echo '  <h1>📦 Repozytorium OPKG dla Enigma2</h1>' >> build/index.html
          echo '  <p>Aby dodać repozytorium, połącz się z tunerem przez SSH i wykonaj komendę:</p>' >> build/index.html
          echo '  <pre><code>echo "src/gz azman-repo-all https://azman26.github.io/azman-enigma2-repo/all" > /etc/opkg/azman.conf</code></pre>' >> build/index.html
          echo '  <h2>Dostępne architektury i paczki</h2>' >> build/index.html

          for arch_dir in all armv7ahf-neon mips32el; do
            if [ -d "build/$arch_dir" ]; then
              echo "  <h3>$arch_dir</h3>" >> build/index.html
              echo "  <p>Lista paczek:</p>" >> build/index.html
              echo "  <ul>" >> build/index.html
              for pkg in $(ls build/$arch_dir/*.ipk 2>/dev/null | sort); do
                pkg_file=$(basename "$pkg")
                echo "    <li><a href=\"$arch_dir/$pkg_file\">$pkg_file</a></li>" >> build/index.html
              done
              echo "  </ul>" >> build/index.html
            fi
          done

          echo '  <h2>Instalacja pakietów</h2>' >> build/index.html
          echo '  <pre><code># Zaktualizuj listę pakietów' >> build/index.html
          echo 'opkg update' >> build/index.html
          echo '# Zainstaluj wybrany pakiet (np. e2iplayer)' >> build/index.html
          echo 'opkg install enigma2-plugin-extensions-e2iplayer' >> build/index.html
          echo '</code></pre>' >> build/index.html
          echo '  <p>Repozytorium przygotowane przez <strong>azman</strong>.</p>' >> build/index.html
          echo '</body>' >> build/index.html
          echo '</html>' >> build/index.html
        shell: bash

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true
