name: Build OPKG Index and Deploy to gh-pages branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # Nadajemy uprawnienia tylko do odczytu i zapisu zawartości
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate OPKG Indexes using Docker
        run: |
          echo "Running opkg-build-index inside the OFFICIAL OpenWrt SDK Docker container..."
          docker run --rm --user $(id -u):$(id -g) -v "$(pwd):/work" ghcr.io/openwrt/sdk:x86_64-22.03.5 /bin/sh -c '
            cd /work
            for arch_dir in all armv7ahf-neon mips32el; do
              if [ -d "$arch_dir" ]; then
                echo "--> Processing directory: $arch_dir"
                cd "$arch_dir"
                opkg-build-index -o Packages .
                gzip -c Packages > Packages.gz
                rm Packages
                cd ..
              fi
            done
            echo "Index generation complete."
          '
          
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          # Opcjonalnie: czyści historię gałęzi gh-pages przy każdym wdrożeniu
          force_orphan: true 