name: Build OPKG Index

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fix apt sources and install opkg-utils
        run: |
          # The 'Nuke and Pave' approach. This is the definitive fix.
          # We overwrite the problematic cloud-init sources.list with the official, canonical one.
          echo "--- Overwriting /etc/apt/sources.list with canonical Ubuntu sources ---"
          sudo tee /etc/apt/sources.list >/dev/null <<'EOF'
          deb http://archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse
          deb http://archive.ubuntu.com/ubuntu/ jammy-updates main restricted universe multiverse
          deb http://archive.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
          EOF

          echo "--- Verifying new sources.list content ---"
          cat /etc/apt/sources.list

          # Now, with a clean and standard source list, update and install.
          echo "--- Updating package list and installing ---"
          sudo apt-get update
          sudo apt-get install -y opkg-utils

      - name: Generate OPKG Indexes
        run: |
          for arch in */; do
            if [ -d "$arch" ] && [ "$arch" != ".github/" ]; then
              echo "-> Processing architecture: ${arch%/}"
              cd "$arch"
              rm -f Packages Packages.gz
              opkg-build-index -o Packages -p Packages.gz .
              cd ..
            fi
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Automatyczna aktualizacja indeksów OPKG [ci skip]"
            git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
          else
            echo "Brak zmian w indeksach. Nic do wysłania."
          fi