name: Build OPKG Index

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          pip install opkg-utils

      - name: Generate OPKG index
        run: |
          opkg-utils/opkg-make-index all > all/Packages
          gzip -kf all/Packages

      - name: Commit and push Packages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add all/Packages all/Packages.gz
          git commit -m "Update OPKG index [skip ci]" || echo "No changes to commit"
          git push
