name: Build OPKG Index and Deploy to gh-pages branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate OPKG Indexes using Python script
        run: |
          for arch_dir in all armv7ahf-neon mips32el; do
            if [ -d "$arch_dir" ]; then
              echo "Processing $arch_dir"
              # Poprawne wywołanie bez -r, bo -r wymaga pliku a nie katalogu
              python3 ./opkg-utils/opkg-make-index "$arch_dir" > "$arch_dir/Packages"
              gzip -c "$arch_dir/Packages" > "$arch_dir/Packages.gz"
              rm "$arch_dir/Packages"
            fi
          done
        shell: bash

      - name: Generate custom HTML index file
        run: |
          echo '<!DOCTYPE html>' > index.html
          echo '<html lang="pl">' >> index.html
          echo '<head>' >> index.html
          echo '  <meta charset="UTF-8">' >> index.html
          echo '  <title>Repozytorium OPKG - Azman</title>' >> index.html
          echo '</head>' >> index.html
          echo '<body>' >> index.html
          echo '  <h1>📦 Repozytorium OPKG dla Enigma2</h1>' >> index.html
          echo '  <p>Dodaj poniższy feed do swojego tunera Enigma2:</p>' >> index.html
          echo '  <pre><code>src/gz azman-all https://azman26.github.io/azman-enigma2-repo/all</code></pre>' >> index.html
          echo '  <h2>Dostępne architektury</h2>' >> index.html
          echo '  <ul>' >> index.html
          echo '    <li><a href="all/">all/</a> – pakiety niezależne od architektury</li>' >> index.html
          echo '  </ul>' >> index.html
          echo '  <h2>Przykładowa instalacja</h2>' >> index.html
          echo '  <pre><code>opkg update' >> index.html
          echo 'opkg install plugin.nazwa</code></pre>' >> index.html
          echo '  <p>Repozytorium przygotowane przez <strong>azman</strong>.</p>' >> index.html
          echo '</body>' >> index.html
          echo '</html>' >> index.html
        shell: bash

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true
