name: Build OPKG Index and Deploy to gh-pages branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show current directory
        run: pwd

      - name: List root directory contents
        run: ls -l

      - name: Show opkg-utils directory contents
        run: ls -l opkg-utils

      - name: Generate OPKG Indexes using Python script
        run: |
          for arch_dir in all armv7ahf-neon mips32el; do
            if [ -d "$arch_dir" ]; then
              echo "Processing $arch_dir"
              rm -f "$arch_dir/Packages" "$arch_dir/Packages.gz"
              python3 ./opkg-utils/opkg-make-index "$arch_dir" > "$arch_dir/Packages"
              gzip -c "$arch_dir/Packages" > "$arch_dir/Packages.gz"
              echo "First 20 lines of $arch_dir/Packages:"
              head -20 "$arch_dir/Packages"
            else
              echo "Directory $arch_dir does not exist, skipping."
            fi
          done
        shell: bash

      - name: Generate HTML index files for browsing
        run: |
          echo "Generating HTML index files..."
          for dir in . all armv7ahf-neon mips32el; do
            if [ -d "$dir" ]; then
              echo "<html><head><title>Index of /$dir</title></head><body><h1>Index of /$dir</h1><hr><pre>" > "$dir/index.html"
              for item in "$dir"/*; do
                if [[ "$(basename "$item")" != "index.html" ]]; then
                  echo "<a href=\"$(basename "$item")\">$(basename "$item")</a>" >> "$dir/index.html"
                fi
              done
              echo "</pre><hr></body></html>" >> "$dir/index.html"
            fi
          done
        shell: bash

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true
