name: Build OPKG Index and Deploy to gh-pages branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate OPKG indexes
        run: |
          for arch_dir in all armv7ahf-neon mips32el; do
            if [ -d "$arch_dir" ]; then
              echo "Processing $arch_dir"
              python3 opkg-utils/opkg-make-index -r "$arch_dir" > "$arch_dir/Packages"
              gzip -c "$arch_dir/Packages" > "$arch_dir/Packages.gz"
              rm "$arch_dir/Packages"
            fi
          done

      - name: Generate HTML index files
        run: |
          for dir in . all armv7ahf-neon mips32el; do
            if [ -d "$dir" ]; then
              echo "<html><head><title>Index of /$dir</title></head><body><h1>Index of /$dir</h1><hr><pre>" > "$dir/index.html"
              for item in "$dir"/*; do
                if [[ "$(basename "$item")" != "index.html" ]]; then
                  echo "<a href=\"$(basename "$item")\">$(basename "$item")</a>" >> "$dir/index.html"
                fi
              done
              echo "</pre><hr></body></html>" >> "$dir/index.html"
            fi
          done

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./all
