name: Build OPKG Index

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # --- POCZĄTEK ZMIANY ---
    # Dodaj tę sekcję, aby nadać akcji uprawnienia do zapisu
    permissions:
      contents: write
    # --- KONIEC ZMIANY ---

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install opkg-utils
        run: |
          sudo apt-get update
          sudo apt-get install -y opkg-utils

      - name: Generate OPKG Indexes
        run: |
          # Pętla po wszystkich podkatalogach
          for arch in */; do
            if [ -d "$arch" ] && [ "$arch" != ".github/" ]; then
              echo "-> Processing architecture: ${arch%/}"
              cd "$arch"
              rm -f Packages Packages.gz
              opkg-build-index -o Packages -p Packages.gz .
              cd ..
            fi
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          # Sprawdź, czy są zmiany
          if ! git diff-index --quiet HEAD; then
            git commit -m "Automatyczna aktualizacja indeksów OPKG [ci skip]"
            # Użyj GITHUB_TOKEN do autoryzacji pusha
            git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
          else
            echo "Brak zmian w indeksach. Nic do wysłania."
          fi