- name: Generate OPKG Indexes using Official OpenWrt Docker SDK
  run: |
    echo "Running opkg-make-index inside the OFFICIAL OpenWrt SDK Docker container..."

    docker run --rm --user $(id -u):$(id -g) -v "$(pwd):/work" ghcr.io/openwrt/sdk:x86_64-22.03.5 /bin/sh -c '
      cd /work
      for arch_dir in all armv7ahf-neon mips32el; do
        if [ -d "$arch_dir" ]; then
          echo "--> Processing directory: $arch_dir"
          cd "$arch_dir"

          opkg-make-index . > Packages
          gzip -kf Packages

          cd ..
        fi
      done
      echo "Index generation complete."
    '
