name: Build OPKG Index

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install opkg-utils
        run: sudo apt-get update && sudo apt-get install -y opkg-utils

      - name: Generate OPKG Indexes (native)
        run: |
          for arch_dir in all armv7ahf-neon mips32el; do
            if [ -d "$arch_dir" ]; then
              echo "--> Processing directory: $arch_dir"
              cd "$arch_dir"

              opkg-make-index . > Packages
              gzip -kf Packages

              cd ..
            fi
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Automatyczna aktualizacja indeksów OPKG [ci skip]"
            git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
          else
            echo "Brak zmian w indeksach. Nic do wysłania."
