name: Build OPKG Index and Deploy to gh-pages branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- POPRAWKA ---
      # Krok 1: Napraw końcówki linii w skrypcie (CRLF -> LF)
      # Ten krok jest kluczowy do rozwiązania błędu '/usr/bin/env: ‘python\r’: No such file or directory'
      - name: Fix script line endings
        run: |
          # Instalujemy dos2unix, jeśli nie ma, i konwertujemy plik.
          # Używamy 'sudo' bo to maszyna GitHub Actions.
          sudo apt-get update
          sudo apt-get install -y dos2unix
          dos2unix ./opkg-utils/opkg-make-index

      # Krok 2: Nadaj uprawnienia do wykonania
      - name: Make opkg-make-index executable
        run: chmod +x ./opkg-utils/opkg-make-index
        shell: bash

      # Krok 3: Generowanie indeksów OPKG - bez zmian
      - name: Generate OPKG Indexes using opkg-make-index script
        run: |
          for arch_dir in all armv7ahf-neon mips32el; do
            if [ -d "$arch_dir" ]; then
              echo "Processing $arch_dir"
              ./opkg-utils/opkg-make-index -r "$arch_dir" > "$arch_dir/Packages"
              gzip -c "$arch_dir/Packages" > "$arch_dir/Packages.gz"
              rm "$arch_dir/Packages"
            else
              echo "Directory $arch_dir does not exist, skipping."
            fi
          done
        shell: bash

      # Krok 4: Generowanie pliku HTML - bez zmian
      - name: Generate custom HTML index file
        run: |
          echo '<!DOCTYPE html>' > index.html
          echo '<html lang="pl">' >> index.html
          echo '<head>' >> index.html
          echo '  <meta charset="UTF-8" />' >> index.html
          echo '  <title>Repozytorium OPKG - Azman</title>' >> index.html
          echo '</head>' >> index.html
          echo '<body>' >> index.html
          echo '  <h1>📦 Repozytorium OPKG dla Enigma2</h1>' >> index.html
          echo '  <p>Dodaj poniższy feed do swojego tunera Enigma2:</p>' >> index.html
          echo '  <pre><code>src/gz azman-all https://azman26.github.io/azman-enigma2-repo/all</code></pre>' >> index.html
          echo '  <h2>Dostępne architektury</h2>' >> index.html
          echo '  <ul>' >> index.html
          echo '    <li><a href="all/">all/</a> – pakiety niezależne od architektury</li>' >> index.html
          echo '    <li><a href="armv7ahf-neon/">armv7ahf-neon/</a></li>' >> index.html
          echo '    <li><a href="mips32el/">mips32el/</a></li>' >> index.html
          echo '  </ul>' >> index.html
          echo '  <h2>Przykładowa instalacja</h2>' >> index.html
          echo '  <pre><code>opkg update' >> index.html
          echo 'opkg install plugin.nazwa</code></pre>' >> index.html
          echo '  <p>Repozytorium przygotowane przez <strong>azman</strong>.</p>' >> index.html
          echo '</body>' >> index.html
          echo '</html>' >> index.html
        shell: bash

      # Krok 5: Wdrożenie na GitHub Pages - bez zmian
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true