name: Build OPKG Index and Deploy to gh-pages branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make opkg-make-index executable
        run: chmod +x ./opkg-utils/opkg-make-index

      - name: Generate OPKG Indexes
        run: |
          for arch_dir in all armv7ahf-neon mips32el; do
            if [ -d "$arch_dir" ]; then
              echo "✅ Found and processing directory: $arch_dir"
              ./opkg-utils/opkg-make-index "$arch_dir" > "$arch_dir/Packages"
              gzip -c "$arch_dir/Packages" > "$arch_dir/Packages.gz"
            else
              echo "ℹ️ Directory $arch_dir does not exist, skipping."
            fi
          done
        shell: bash

      - name: Validate Packages.gz files
        run: |
          for arch_dir in all armv7ahf-neon mips32el; do
            if [ -f "$arch_dir/Packages.gz" ]; then
              echo "🔍 Checking $arch_dir/Packages.gz..."
              if [ ! -s "$arch_dir/Packages.gz" ]; then
                echo "❌ ERROR: $arch_dir/Packages.gz is empty!"
                exit 1
              fi
              # Zmieniamy walidację, aby sprawdzała pole SHA256Sum
              PKG_COUNT=$(gunzip -c "$arch_dir/Packages.gz" | grep -c "^SHA256Sum:")
              if [ "$PKG_COUNT" -eq 0 ]; then
                echo "❌ ERROR: $arch_dir/Packages.gz does not contain any package entries!"
                exit 1
              fi
              echo "✅ $arch_dir/Packages.gz is valid — found $PKG_COUNT packages."
            else
              echo "⚠️ WARNING: $arch_dir/Packages.gz not found, skipping."
            fi
          done
        shell: bash

      # Reszta kroków (generowanie HTML, deploy) pozostaje bez zmian...
      - name: Generate custom HTML index file (main)
        run: |
          # ... (bez zmian)
          echo '<!DOCTYPE html>' > index.html
          echo '<html lang="pl">' >> index.html
          echo '<head>' >> index.html
          echo '  <meta charset="UTF-8" />' >> index.html
          echo '  <title>Repozytorium OPKG - Azman</title>' >> index.html
          echo '</head>' >> index.html
          echo '<body>' >> index.html
          echo '  <h1>📦 Repozytorium OPKG dla Enigma2</h1>' >> index.html
          echo '  <p>Aby dodać repozytorium, połącz się z tunerem i wykonaj komendę:</p>' >> index.html
          echo '  <pre><code>echo "src/gz azman-feed-all https://azman26.github.io/azman-enigma2-repo/all" > /etc/opkg/azman-feed.conf</code></pre>' >> index.html
          echo '  <h2>Dostępne architektury</h2>' >> index.html
          echo '  <ul>' >> index.html
          if [ -d "all" ]; then echo '    <li><a href="all/">all/</a> – pakiety niezależne od architektury (skórki, picony, wtyczki python)</li>' >> index.html; fi
          if [ -d "armv7ahf-neon" ]; then echo '    <li><a href="armv7ahf-neon/">armv7ahf-neon/</a> – pakiety dla procesorów ARM</li>' >> index.html; fi
          if [ -d "mips32el" ]; then echo '    <li><a href="mips32el/">mips32el/</a> – pakiety dla procesorów MIPS</li>' >> index.html; fi
          echo '  </ul>' >> index.html
          echo '  <h2>Instalacja pakietów</h2>' >> index.html
          echo '  <pre><code># Zaktualizuj listę pakietów' >> index.html
          echo 'opkg update' >> index.html
          echo '# Zainstaluj wybrany pakiet (np. AzmanPanel)' >> index.html
          echo 'opkg install enigma2-plugin-extensions-AzmanPanel' >> index.html
          echo '</code></pre>' >> index.html
          echo '  <p>Repozytorium przygotowane przez <strong>azman</strong>.</p>' >> index.html
          echo '</body>' >> index.html
          echo '</html>' >> index.html
        shell: bash

      - name: Generate HTML index in all directory
        run: |
          # ... (bez zmian)
          if [ -d "all" ] && [ -f "all/Packages" ]; then
            echo "Generuję index.html w katalogu all"
            echo '<!DOCTYPE html>' > all/index.html
            echo '<html lang="pl"><head><meta charset="UTF-8"><title>Pakiety all</title></head><body>' >> all/index.html
            echo '<h1>Pakiety w katalogu all</h1>' >> all/index.html
            echo '<ul>' >> all/index.html

            awk -v repo_url="https://raw.githubusercontent.com/azman26/azman-enigma2-repo/gh-pages/all" '
            BEGIN { pkg=""; ver=""; }
            /^Package:/ { pkg=$2; }
            /^Version:/ { ver=$2; }
            /^$/ {
              if (pkg != "") {
                printf "<li><a href=\"" repo_url "/%s.ipk\"><b>%s</b></a> — wersja %s</li>\n", pkg, pkg, ver;
              }
              pkg=""; ver="";
            }
            END {
              if (pkg != "") {
                printf "<li><a href=\"" repo_url "/%s.ipk\"><b>%s</b></a> — wersja %s</li>\n", pkg, pkg, ver;
              }
            }
            ' all/Packages >> all/index.html

            echo '</ul></body></html>' >> all/index.html
          else
            echo "Katalog all lub plik Packages nie istnieje, pomijam generowanie index.html w all"
          fi
        shell: bash
      
      - name: Add .nojekyll file to prevent GitHub Pages Jekyll processing
        run: touch .nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true