name: Build OPKG Index

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install opkg-utils
        run: |
          echo "--- Modifying sources.list to add 'universe' repository ---"
          sudo sed -i 's/ main/ main universe/g' /etc/apt/sources.list
          echo "--- Verifying modification ---"
          cat /etc/apt/sources.list
          
          echo "--- Updating package list and installing ---"
          sudo apt-get update
          sudo apt-get install -y opkg-utils

      - name: Generate OPKG Indexes
        run: |
          for arch in */; do
            if [ -d "$arch" ] && [ "$arch" != ".github/" ]; then
              echo "-> Processing architecture: ${arch%/}"
              cd "$arch"
              rm -f Packages Packages.gz
              opkg-build-index -o Packages -p Packages.gz .
              cd ..
            fi
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Automatyczna aktualizacja indeksów OPKG [ci skip]"
            git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
          else
            echo "Brak zmian w indeksach. Nic do wysłania."
          fi