name: Build OPKG Index

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate OPKG Indexes using Docker
        run: |
          echo "Running opkg-build-index inside an OpenWrt SDK Docker container..."
          docker run --rm -v "$(pwd):/work" openwrtorg/sdk:x86-64-21.02.3 /bin/sh -c '
            cd /work
            for arch_dir in all armv7ahf-neon mips32el; do
              if [ -d "$arch_dir" ]; then
                echo "--> Processing directory: $arch_dir"
                cd "$arch_dir"
                # The SDK contains the indexer script. We redirect its output to create the Packages file.
                /work/scripts/ipkg-build-index.sh . > Packages
                gzip -c Packages > Packages.gz
                rm Packages
                cd ..
              fi
            done
            echo "Index generation complete."
          '

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Automatyczna aktualizacja indeksów OPKG [ci skip]"
            git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
          else
            echo "Brak zmian w indeksach. Nic do wysłania."
          fi