name: Build OPKG Index and Deploy to gh-pages branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate OPKG Indexes using Python script
        run: |
          for arch_dir in all armv7ahf-neon mips32el; do
            if [ -d "$arch_dir" ]; then
              echo "Processing $arch_dir"
              python3 ./opkg-utils/opkg-make-index -r "$arch_dir" > "$arch_dir/Packages"
              gzip -c "$arch_dir/Packages" > "$arch_dir/Packages.gz"
              rm "$arch_dir/Packages"
            fi
          done
        shell: bash

      - name: Generate custom HTML index file
        run: |
          cat > index.html <<EOF
<!DOCTYPE html>
<html lang="pl">
<head>
  <meta charset="UTF-8">
  <title>Repozytorium OPKG - Azman</title>
</head>
<body>
  <h1>📦 Repozytorium OPKG dla Enigma2</h1>
  <p>Dodaj poniższy feed do swojego tunera Enigma2:</p>

  <pre><code>src/gz azman-all https://azman26.github.io/azman-enigma2-repo/all</code></pre>

  <h2>Dostępne architektury</h2>
  <ul>
    <li><a href="all/">all/</a> – pakiety niezależne od architektury</li>
  </ul>

  <h2>Przykładowa instalacja</h2>
  <pre><code>opkg update
opkg install plugin.nazwa</code></pre>

  <p>Repozytorium przygotowane przez <strong>azman</strong>.</p>
</body>
</html>
EOF
        shell: bash

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true
